language: node_js

node_js:
    - "5"
    - "5.1"
    - "4"
    - "4.2"
    - "4.1"
    - "4.0"
    - "0.12"
    - "0.11"
    - "0.10"
    - "0.8"
    - "0.6"

before_script:
    - npm install -g gulp
    - npm install

script:
    - node tests/prepare_tests.js
    - gulp --gulpfile tests/gulpfile.js dump
